---
# config

common:
  scenario: ./scenario
  cfg_file : ql2.sumocfg
  net_file : ql1.net.xml
  det_file : ql2.det.xml
  port : 8819
  server_ip : #add your ip address here
  total_episodes : 20
  log_level : info

sumo:
  start : True,
  quit_on_end : True
  num_clients : 2
  use_gui : True
  endpoints : ['E20','-E19']
  badpoints : ['E5','E2','E13']
  successend : ["E20"]

